version: "3.9"
services:
  app:
    container_name: backend
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/user/src/app
    depends_on:
      - db

  # PostgreSQL service
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=vectigal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
