version: "3.9"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/user/src/app
      - ./frontend/node_modules:/user/src/app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes if necessary
    stdin_open: true
    tty: true

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/user/src/app
    depends_on:
      - db

  # PostgreSQL service
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=vectigal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
